### ISSUE TITLE
你的wifi模块能正常工作吗？

### ISSUE THREAD

**Issue by WooDwayToneTion** [Gah0/android_xiaomi_kernel_grus#1]
我的机型是红米NOTE 5A
我尝试添加了高通的驱动源码 drivers/staging/prima   
更改了必要的Kconfig、Makfile以及ugglite_msm8937_defconfig 
替换boot.img发现还是不行 
miui的界面里打不开wifi
能在adb中ifconfig wlan0 up  但是不能切换信道 也不能iwconfig wlan0 mode

**Comment by Gah0** [comment]
我没有使用过红米note5a，我只能说说我自己解决wifi的一些经验。

先看看wifi驱动有没有被加载，或者有没有irq
`adb shell dmesg >D:/dmesg.log`

miui上编译内核比较多坑，有的手机用的是qcacld，有的是prima。我分享一下我的两种方法。

1. 编译成wifi模块，首先是要去掉内核config中的`CONFIG_MODULE_SIG`模块签名认证，还需要需要找找3.18内核版本 强制跳过模块版本检查的[commit](https://github.com/Gah0/android_xiaomi_kernel_grus/commit/f1cb1374b9c5c536bc36efae7539ebc7eca9ee47)。然后加入wifi驱动，然后最好编译为模块，即config中的值设置为m，生成.ko文件，放入lib/modules，替换原来的wifi模块。

2. ad-hoc功能，我对这个了解不是很足够，但是我建议在menuconfig中把所有关于prima wlan的内核选项打开了再编译试试。

3. 通过adb shell跟踪驱动函数。

**Comment by WooDwayToneTion** [comment]
谢谢 ，
我又弄了一下 ，好像是MIUI的界面开关和wlan.ko的加载冲突了。
我的其实已经弄好了。。。。
没办法制定信道好像就是手机网卡的尿性。
但是它这个网卡又支持ad-hoc模式，就很抽象。
